blueprint:
  name: Tuya TS0044 (Zigbee2MQTT) - 4 Buttons 4 Layers
  description: "Wielowarstwowa obsługa pilota TS0044 przez Zigbee2MQTT. 
    Przytrzymanie przycisku 4 zmienia warstwy. 
    Wymaga pomocnika input_select.pilot_layers"
  domain: automation
  input:
    remote:
      name: Remote Sensor
      description: Wybierz sensor 'action' Twojego pilota (np. sensor.0x..._action)
      selector:
        entity:
          domain: sensor
          multiple: false
    layer_select:
      name: Pomocnik Warstw
      description: Wybierz utworzony input_select do zarządzania warstwami
      selector:
        entity:
          domain: input_select
          
    # PRZYCISK 1
    b1_l1:
      name: "P1: Warstwa 1"
      default: []
      selector:
        action: {}
    b1_l2:
      name: "P1: Warstwa 2"
      default: []
      selector:
        action: {}
    b1_l3:
      name: "P1: Warstwa 3"
      default: []
      selector:
        action: {}
    b1_l4:
      name: "P1: Warstwa 4"
      default: []
      selector:
        action: {}

    # PRZYCISK 2
    b2_l1:
      name: "P2: Warstwa 1"
      default: []
      selector:
        action: {}
    b2_l2:
      name: "P2: Warstwa 2"
      default: []
      selector:
        action: {}
    b2_l3:
      name: "P2: Warstwa 3"
      default: []
      selector:
        action: {}
    b2_l4:
      name: "P2: Warstwa 4"
      default: []
      selector:
        action: {}

    # PRZYCISK 3
    b3_l1:
      name: "P3: Warstwa 1"
      default: []
      selector:
        action: {}
    b3_l2:
      name: "P3: Warstwa 2"
      default: []
      selector:
        action: {}
    b3_l3:
      name: "P3: Warstwa 3"
      default: []
      selector:
        action: {}
    b3_l4:
      name: "P3: Warstwa 4"
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote

action:
  - variables:
      action_value: "{{ trigger.to_state.state }}"
      current_layer: "{{ states(layer_select) }}"

  - choose:
      # --- LOGIKA ZMIANY WARSTW (HOLD BUTTON 4) ---
      - conditions: "{{ action_value == '4_hold' }}"
        sequence:
          - service: input_select.select_next
            target:
              entity_id: !input layer_select

      # --- PRZYCISK 1 ---
      - conditions: "{{ action_value == '1_single' }}"
        sequence:
          - choose:
              - conditions: "{{ current_layer == 'Layer 1' }}"
                sequence: !input b1_l1
              - conditions: "{{ current_layer == 'Layer 2' }}"
                sequence: !input b1_l2
              - conditions: "{{ current_layer == 'Layer 3' }}"
                sequence: !input b1_l3
              - conditions: "{{ current_layer == 'Layer 4' }}"
                sequence: !input b1_l4

      # --- PRZYCISK 2 ---
      - conditions: "{{ action_value == '2_single' }}"
        sequence:
          - choose:
              - conditions: "{{ current_layer == 'Layer 1' }}"
                sequence: !input b2_l1
              - conditions: "{{ current_layer == 'Layer 2' }}"
                sequence: !input b2_l2
              - conditions: "{{ current_layer == 'Layer 3' }}"
                sequence: !input b2_l3
              - conditions: "{{ current_layer == 'Layer 4' }}"
                sequence: !input b2_l4

      # --- PRZYCISK 3 ---
      - conditions: "{{ action_value == '3_single' }}"
        sequence:
          - choose:
              - conditions: "{{ current_layer == 'Layer 1' }}"
                sequence: !input b3_l1
              - conditions: "{{ current_layer == 'Layer 2' }}"
                sequence: !input b3_l2
              - conditions: "{{ current_layer == 'Layer 3' }}"
                sequence: !input b3_l3
              - conditions: "{{ current_layer == 'Layer 4' }}"
                sequence: !input b3_l4